spring.application.name=TP_5_Docker

server.port=8000

spring.datasource.url=jdbc:mysql://localhost:3306/tp5_auth_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.security.master-key=tp5-master-key-2026
app.security.smk=tp5-secret-smk-2026